### ISSUE TITLE
Remove the use of '/' in addons paths.

### ISSUE THREAD

**Issue by gaspard** [cerebral/cerebral-addons#25]
Now that the standard way of describing paths inside the state tree is by using dots like this: `some.deep.path` I think it is a good idea to remove the use of slashes inside addons path descriptions. The `:/` makes it look like an uri when it is not. Users then tend to write `state:/some/deep/path` and get confused on why it does not work.

Proposition: simply remove all '/' and use `input:some.deep.path`:

```Javascript
const re = /^(input|output|state):(([a-zA-Z_]+\.?)*)$/
const [ _, scheme, path ] = re.exec ( 'input:some.dee.path' )
```

**Comment by christianalfoni** [comment]
Yeah, I think the url-scheme was a good start, but as we know have much confident in its use I think we can take the liberty to make it a "Cerebral thing". It should also be easy to migrate as you do a search and replace on `input:/` and `state:/`.

If we vote up this I change I suggest we implement inside Cerebral. And we make Cerebral aware of what and `input`, an `output` and the `state` is. The state differs as we use both the `get` and `set` method on it. What that basically comes down to is that `input` and `output` use normal JS mutation, but everything else use this signature: `whateverSet(path, value)` and `whateverGet(path)`.

this means that any context provider adding something to the context with a `set` and a `get` method will be usable by these "addons".

An example of this would be modules provider, which adds `module` to the context. Since `module.state` has a `get` and `set` method, it will work using: `module.state:some.path`

**Comment by TomKaltz** [comment]
+1

**Comment by garth** [comment]
So I guess we'll leave behind the URL format for something more cerebral specific.

If we move this to cerebral core then maybe it's time to move some of the "core" addons over also?

**Comment by christianalfoni** [comment]
I think it would be nice to bump up to breaking feature on addons with the new syntax. Then we can try it out. When we are happy we can decide how and what to move to core.

I have not looked at these setters and getters... they are brilliant! Was not aware of this at all :) So we should bring out these features for sure!

About debounce there is still some discussion to do. We can not quite use them like @gaspard suggested, sorry I had 3 beers in me, so did not pick up on it:

```js
[
  debounce(200),
  actionRun
]
```
So this does not work. The reason is that the signals that should be debounced has to "go somewhere". So basically it needs to work like this:

```js
[
  debounce(200), {
    continue: []
  }
]
```
Which means that : 

```js
[
  debounce(200), {
    continue: []
  },
  actionB // I will always run
]
```
But! I think we are missing out on something awesome thinking traditionally. What we are actually able to do now is:


```js
[
  debounce(200), {
    ignored: [], // Handle debounced signals
    accepted: [] // Handle accepted signals
  },
  actionB // I will always run
]
```
Signals are something different than observable streams so we have to implement these things "the signal" way. Take advantage of their advantages, like above where we can actually add behaviour specifically to ignored signals. And we can actually debounce different parts of the flow. I think that makes them more powerful as you get the streams behaviour, but aditions to it. Same for the other ones:

```js
[
  throttle(200), {
    ignored: [],
    accepted: []
  },
  filter('input:completed'), {
    ignored: [],
    accepted: []
  }
]
```

So yeah, I would argue this is a really good thing :) It will not work exactly like streams, because signals are not streams, but they are more flexible :)

**Comment by gaspard** [comment]
@christianalfoni Strangely, my debounce solution seems ok. Not having the ignored actions go anywhere is maybe not so good with cerebral internals but I did not see anything bad happening.

Anyway, I think you proposal is better and `ignored`, `accepted` seems like nice choices for all the a/b actions (instead of `true`, `false`, `continue`, etc).

**Comment by christianalfoni** [comment]
What I suggest we do is implement, as also suggested by @bfitch , is implement a concept of "operators" in Cerebral core. That means we keep `cerebral-addons` as is, but we can deprecate it later.

The operators is inspired by `cerebral-addons`, but uses this new syntax and we create a convention on naming paths. To give some more insight I am thinking we can implement like this: https://gist.github.com/christianalfoni/1ab82be5d4d7c58805a0a09acf032695. 

```js
import {set, copy} from 'cerebral/operators';

export default [
  set('state:foo', 'bar'),
  copy('input:foo', 'state:bar')
]
```

**Comment by garth** [comment]
Sounds like a doable task for the weekend

**Comment by Guria** [comment]
done
